"""Performance review export formatters."""

import json
from typing import Dict, Any, List
from abc import ABC, abstractmethod
from io import BytesIO

try:
    from PIL import Image, ImageDraw, ImageFont
    HAS_PIL = True
except ImportError:
    HAS_PIL = False


class ReviewExporter(ABC):
    """Base class for review exporters."""

    @abstractmethod
    def export(self, review_data: Dict[str, Any]) -> str:
        """Export review data to format-specific string."""
        pass


class JSONExporter(ReviewExporter):
    """Export review data as JSON."""

    def export(self, review_data: Dict[str, Any]) -> str:
        """Export to formatted JSON."""
        return json.dumps(review_data, indent=2)


class MarkdownExporter(ReviewExporter):
    """Export review data as Markdown."""

    def export(self, review_data: Dict[str, Any]) -> str:
        """Export to Markdown format."""
        lines = []

        # Header
        person = review_data.get('person', {})
        name = person.get('name', 'Unknown')
        team = person.get('team', 'Unknown')
        role = person.get('role', 'Unknown')
        period = review_data.get('period', 'Current')

        lines.append(f"# Performance Review: {name}")
        lines.append(f"\n**Period:** {period}  ")
        lines.append(f"**Team:** {team}  ")
        lines.append(f"**Role:** {role}  ")
        lines.append(f"**Generated:** {review_data.get('generated_at', 'N/A')}\n")

        # Metrics
        lines.append("## Metrics\n")
        metrics = review_data.get('metrics', {})
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Code Volume | {metrics.get('code_volume', 0):,} lines |")
        lines.append(f"| Commits | {metrics.get('commits', 0)} |")
        lines.append(f"| PRs Merged | {metrics.get('prs_merged', 0)} |")
        lines.append(f"| Reviews Given | {metrics.get('reviews_given', 0)} |")
        lines.append(f"| Tickets Closed | {metrics.get('tickets_closed', 0)} |")
        lines.append(f"| Productivity Score | {metrics.get('productivity_score', 0):.0f}/100 |")
        lines.append(f"| Review Quality Score | {metrics.get('review_quality_score', 0):.0f}/100 |")
        lines.append(f"| Collaboration Score | {metrics.get('collaboration_score', 0):.0f}/100 |\n")

        # Peer Comparison
        lines.append("## Peer Comparison\n")
        comparison = review_data.get('peer_comparison', {})
        if comparison:
            for metric, assessment in comparison.items():
                lines.append(f"- **{metric.replace('_', ' ').title()}**: {assessment}")
            lines.append("")
        else:
            lines.append("No peer comparison data available.\n")

        # Velocity Trend
        lines.append("## Productivity Trend\n")
        trend = review_data.get('velocity_trend', {})
        if trend.get('status') == 'calculated':
            lines.append(f"**Status:** Trend calculated\n")
            metrics_trend = trend.get('metrics', {})
            for metric, data in metrics_trend.items():
                if isinstance(data, dict):
                    current = data.get('current', 0)
                    pct_change = data.get('pct_change', 0)
                    direction = data.get('trend', 'stable')
                    lines.append(f"- **{metric.replace('_', ' ').title()}**: {current} ({direction}, {pct_change:+.1f}%)")
            lines.append("")
        else:
            lines.append("Insufficient history for trend analysis.\n")

        # Strengths
        lines.append("## Strengths\n")
        strengths = review_data.get('strengths', [])
        if strengths:
            for strength in strengths:
                lines.append(f"- {strength}")
            lines.append("")
        else:
            lines.append("No significant strengths identified.\n")

        # Risks
        lines.append("## Risks & Concerns\n")
        risks = review_data.get('risks', [])
        if risks:
            for risk in risks:
                lines.append(f"- ⚠️ {risk}")
            lines.append("")
        else:
            lines.append("No major risks identified.\n")

        # Recommendations
        lines.append("## Recommendations\n")
        recommendations = review_data.get('recommendations', [])
        for rec in recommendations:
            lines.append(f"- {rec}")
        lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by ManagerTools Dashboard*")

        return "\n".join(lines)


class PDFExporter(ReviewExporter):
    """Export review data as PDF."""

    def export(self, review_data: Dict[str, Any]) -> str:
        """Export to PDF-ready HTML (for conversion to PDF).

        Returns HTML that can be converted to PDF with tools like wkhtmltopdf or weasyprint.
        """
        person = review_data.get('person', {})
        name = person.get('name', 'Unknown')
        team = person.get('team', 'Unknown')
        role = person.get('role', 'Unknown')
        period = review_data.get('period', 'Current')
        metrics = review_data.get('metrics', {})
        comparison = review_data.get('peer_comparison', {})
        strengths = review_data.get('strengths', [])
        risks = review_data.get('risks', [])
        recommendations = review_data.get('recommendations', [])

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Performance Review - {name}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 8.5in;
            margin: 0;
            padding: 0.5in;
            background: white;
        }}
        .header {{
            border-bottom: 2px solid #0066cc;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        h1 {{
            margin: 0 0 15px 0;
            color: #0066cc;
            font-size: 28px;
        }}
        .info-row {{
            display: flex;
            justify-content: space-between;
            margin: 5px 0;
            font-size: 14px;
        }}
        h2 {{
            margin: 25px 0 15px 0;
            color: #0066cc;
            font-size: 18px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }}
        th {{
            background: #f5f5f5;
            font-weight: bold;
        }}
        ul {{
            margin: 10px 0;
            padding-left: 20px;
        }}
        li {{
            margin: 5px 0;
        }}
        .score {{
            font-weight: bold;
            color: #0066cc;
        }}
        .risk {{
            color: #cc0000;
            font-weight: bold;
        }}
        .strength {{
            color: #00aa00;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
            text-align: center;
        }}
        .page-break {{
            page-break-after: always;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Performance Review</h1>
        <div class="info-row">
            <div><strong>Name:</strong> {name}</div>
            <div><strong>Period:</strong> {period}</div>
        </div>
        <div class="info-row">
            <div><strong>Team:</strong> {team}</div>
            <div><strong>Role:</strong> {role}</div>
        </div>
    </div>

    <h2>Key Metrics</h2>
    <table>
        <tr>
            <th>Metric</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Code Volume</td>
            <td>{metrics.get('code_volume', 0):,} lines</td>
        </tr>
        <tr>
            <td>Commits</td>
            <td>{metrics.get('commits', 0)}</td>
        </tr>
        <tr>
            <td>PRs Merged</td>
            <td>{metrics.get('prs_merged', 0)}</td>
        </tr>
        <tr>
            <td>Reviews Given</td>
            <td>{metrics.get('reviews_given', 0)}</td>
        </tr>
        <tr>
            <td>Tickets Closed</td>
            <td>{metrics.get('tickets_closed', 0)}</td>
        </tr>
        <tr>
            <td>Productivity Score</td>
            <td><span class="score">{metrics.get('productivity_score', 0):.0f}/100</span></td>
        </tr>
        <tr>
            <td>Review Quality Score</td>
            <td><span class="score">{metrics.get('review_quality_score', 0):.0f}/100</span></td>
        </tr>
        <tr>
            <td>Collaboration Score</td>
            <td><span class="score">{metrics.get('collaboration_score', 0):.0f}/100</span></td>
        </tr>
    </table>

    <h2>Peer Comparison</h2>
    <ul>
        {self._format_comparison(comparison)}
    </ul>

    <h2>Strengths</h2>
    <ul>
        {''.join(f'<li class="strength">{s}</li>' for s in strengths) if strengths else '<li>No major strengths identified</li>'}
    </ul>

    <h2>Risks & Concerns</h2>
    <ul>
        {''.join(f'<li class="risk">⚠️ {r}</li>' for r in risks) if risks else '<li>No major risks identified</li>'}
    </ul>

    <h2>Recommendations</h2>
    <ul>
        {''.join(f'<li>{r}</li>' for r in recommendations)}
    </ul>

    <div class="footer">
        <p>Generated by ManagerTools Dashboard</p>
        <p>{review_data.get('generated_at', 'N/A')}</p>
    </div>
</body>
</html>
"""
        return html

    @staticmethod
    def _format_comparison(comparison: Dict[str, str]) -> str:
        """Format comparison data as HTML list items."""
        if not comparison:
            return "<li>No peer comparison data available</li>"
        items = [f"<li><strong>{k.replace('_', ' ').title()}:</strong> {v}</li>" for k, v in comparison.items()]
        return "\n        ".join(items)


class PNGExporter(ReviewExporter):
    """Export review data as PNG image."""

    def export(self, review_data: Dict[str, Any]) -> bytes:
        """Export to PNG image (returns binary data)."""
        if not HAS_PIL:
            raise ImportError("Pillow is required for PNG export. Install with: pip install Pillow")

        person = review_data.get('person', {})
        name = person.get('name', 'Unknown')
        team = person.get('team', 'Unknown')
        role = person.get('role', 'Unknown')
        metrics = review_data.get('metrics', {})

        # Create image
        width, height = 800, 1000
        img = Image.new('RGB', (width, height), color='white')
        draw = ImageDraw.Draw(img)

        # Try to use system fonts, fall back to default
        try:
            title_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 24)
            header_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 14)
            text_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 12)
            small_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 10)
        except (OSError, IOError):
            # Fallback for systems without Helvetica
            title_font = ImageFont.load_default()
            header_font = ImageFont.load_default()
            text_font = ImageFont.load_default()
            small_font = ImageFont.load_default()

        y = 20
        margin = 20

        # Title
        draw.text((margin, y), f"Performance Review", font=title_font, fill='#0066cc')
        y += 40

        # Person info
        draw.text((margin, y), f"Name: {name}", font=header_font, fill='#333')
        y += 25
        draw.text((margin, y), f"Team: {team}", font=header_font, fill='#333')
        y += 25
        draw.text((margin, y), f"Role: {role}", font=header_font, fill='#333')
        y += 35

        # Divider
        draw.line([(margin, y), (width - margin, y)], fill='#ddd', width=2)
        y += 20

        # Key metrics
        draw.text((margin, y), "Key Metrics", font=header_font, fill='#0066cc')
        y += 25

        metrics_data = [
            ('Productivity Score', f"{metrics.get('productivity_score', 0):.0f}/100"),
            ('Code Volume', f"{metrics.get('code_volume', 0):,} lines"),
            ('Commits', f"{metrics.get('commits', 0)}"),
            ('PRs Merged', f"{metrics.get('prs_merged', 0)}"),
            ('Reviews Given', f"{metrics.get('reviews_given', 0)}"),
        ]

        for label, value in metrics_data:
            draw.text((margin + 10, y), f"{label}:", font=text_font, fill='#333')
            draw.text((width - margin - 150, y), value, font=text_font, fill='#0066cc')
            y += 22

        y += 15

        # Divider
        draw.line([(margin, y), (width - margin, y)], fill='#ddd', width=2)
        y += 20

        # Strengths
        draw.text((margin, y), "Strengths", font=header_font, fill='#00aa00')
        y += 25

        strengths = review_data.get('strengths', [])
        for strength in strengths[:3]:  # Max 3 to fit on page
            draw.text((margin + 10, y), f"• {strength[:50]}", font=small_font, fill='#333')
            y += 18

        y += 10

        # Risks
        draw.text((margin, y), "Risks & Concerns", font=header_font, fill='#cc0000')
        y += 25

        risks = review_data.get('risks', [])
        for risk in risks[:2]:  # Max 2 to fit
            draw.text((margin + 10, y), f"⚠ {risk[:50]}", font=small_font, fill='#333')
            y += 18

        y += 15

        # Divider
        draw.line([(margin, y), (width - margin, y)], fill='#ddd', width=2)
        y += 20

        # Top recommendation
        recommendations = review_data.get('recommendations', [])
        if recommendations:
            draw.text((margin, y), "Top Recommendation", font=header_font, fill='#0066cc')
            y += 25
            rec_text = recommendations[0][:70]
            draw.text((margin + 10, y), f"→ {rec_text}", font=text_font, fill='#333')

        # Convert to bytes
        output = BytesIO()
        img.save(output, format='PNG')
        return output.getvalue()


class ReviewExporterFactory:
    """Factory for creating review exporters."""

    _exporters = {
        'json': JSONExporter,
        'markdown': MarkdownExporter,
        'pdf': PDFExporter,
    }

    # Add PNG if Pillow is available
    if HAS_PIL:
        _exporters['png'] = PNGExporter

    @classmethod
    def create(cls, format_type: str) -> ReviewExporter:
        """Create an exporter for the given format.

        Args:
            format_type: One of 'json', 'markdown', 'pdf'

        Returns:
            ReviewExporter instance

        Raises:
            ValueError: If format_type is not supported
        """
        if format_type not in cls._exporters:
            raise ValueError(f"Unsupported export format: {format_type}. Supported: {', '.join(cls._exporters.keys())}")
        return cls._exporters[format_type]()

    @classmethod
    def supported_formats(cls) -> List[str]:
        """Get list of supported export formats."""
        return list(cls._exporters.keys())
